[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = src

[env:esp32-s3-devkitc-1]
platform = espressif32
board = openfinger_esp32s3_supermini
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -I../common
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DOPENFINGER_BOARD_TARGET=\"esp32s3\"
    -DOPENFINGER_LED_PIN=48
    -DOPENFINGER_LED_ACTIVE_LOW=0
    -DOPENFINGER_LED_IS_NEOPIXEL=1
