#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tarfile
import zipfile
import hashlib
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build"
DIST = ROOT / "dist"
VERSION_FILE = ROOT / "VERSION"
PROTOCOL_VERSION_FILE = ROOT / "PROTOCOL_VERSION"
GUI_PROJECT = ROOT / "src" / "OpenFinger.Control" / "OpenFinger.Control.csproj"
GUI_DIR = GUI_PROJECT.parent
DRIVER_ROOT = ROOT / "src" / "drivers" / "openfinger"
FIRMWARE_TARGETS: dict[str, tuple[Path, str]] = {
    "esp32c3": (ROOT / "src" / "firmware" / "esp32c3", "esp32-c3-dev-module"),
    "esp32s3": (ROOT / "src" / "firmware" / "esp32s3", "esp32-s3-devkitc-1"),
}
PACKAGE_NATIVE_TOOLS = (
    "openfinger_service.exe",
    "openfinger_controller_bridge.exe",
    "openfinger_adc_monitor.exe",
    "openfinger_firmware_tool.exe",
)
BRIDGE_RUNTIME_FILES = (
    "actions.json",
    "bindings_oculus_touch.json",
    "openfinger_bridge.vrmanifest",
)
PACKAGE_EXCLUDE_SUFFIXES = (".pdb", ".ilk", ".exp", ".lib")
PACKAGE_EXCLUDE_DIRS = {"obj", ".vs", "DesignTimeBuild", "FileContentIndex", "CopilotIndices"}

PROCESS_NAMES = (
    "OpenFinger.Control.exe",
    "OpenFingerControl.exe",
    "openfinger_service.exe",
    "openfinger_controller_bridge.exe",
    "openfinger_adc_monitor.exe",
    "openfinger_firmware_tool.exe",
)
STEAMVR_PACKAGE_NATIVE_TOOLS = (
    "openfinger_service.exe",
    "openfinger_controller_bridge.exe",
    "openfinger_adc_monitor.exe",
    "openfinger_firmware_tool.exe",
)
BRIDGE_RUNTIME_FILES = (
    "actions.json",
    "bindings_oculus_touch.json",
    "openfinger_bridge.vrmanifest",
)
PACKAGE_EXCLUDE_SUFFIXES = (".pdb", ".ilk", ".exp", ".lib")
PACKAGE_EXCLUDE_DIRS = {"obj", ".vs", "DesignTimeBuild", "FileContentIndex", "CopilotIndices"}

PROCESS_NAMES = ("vrmonitor.exe", "vrserver.exe")


def read_text_file(path: Path, fallback: str) -> str:
    if not path.exists():
        return fallback
    value = path.read_text(encoding="utf-8").strip()
    return value or fallback


def version() -> str:
    return read_text_file(VERSION_FILE, "0.1.0")


def protocol_version() -> int:
    return int(read_text_file(PROTOCOL_VERSION_FILE, "2"))


def q(args: list[str]) -> str:
    return " ".join(f'"{item}"' if " " in item else item for item in args)


def run_process(args: list[str], cwd: Path | None = None) -> None:
    print(f"[x.py] {q(args)}")
    subprocess.run(args, cwd=str(cwd or ROOT), check=True)


def remove_tree(path: Path) -> None:
    if path.exists():
        print(f"[x.py] remove {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
        shutil.rmtree(path)


def stop_processes(names: tuple[str, ...]) -> None:
    if os.name != "nt":
        return
    for image_name in names:
        subprocess.run(["taskkill", "/IM", image_name, "/F"], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def generate_version_files() -> None:
    v = version()
    pv = protocol_version()

    cs = GUI_DIR / "Generated" / "OpenFingerVersion.g.cs"
    cs.parent.mkdir(parents=True, exist_ok=True)
    cs.write_text(
        f'''// <auto-generated />\nnamespace OpenFinger.Control;\n\npublic static class OpenFingerVersion\n{{\n    public const string Version = "{v}";\n    public const int ProtocolVersion = {pv};\n    public const string Display = "OpenFinger {v} / Protocol v{pv}";\n}}\n''',
        encoding="utf-8",
    )

    fw = ROOT / "src" / "firmware" / "common" / "openfinger_version.h"
    fw.parent.mkdir(parents=True, exist_ok=True)
    fw.write_text(
        f'''#pragma once\n\n#define OPENFINGER_PRODUCT_VERSION "{v}"\n#define OPENFINGER_FIRMWARE_VERSION OPENFINGER_PRODUCT_VERSION\n#define OPENFINGER_PROTOCOL_VERSION {pv}\n''',
        encoding="utf-8",
    )

    manifests = [
        DRIVER_ROOT / "driver.vrdrivermanifest",
        ROOT / "src" / "OpenFinger.ControllerBridge" / "resources" / "openfinger_bridge.vrmanifest",
    ]
    for manifest in manifests:
        if not manifest.exists():
            continue
        data = json.loads(manifest.read_text(encoding="utf-8"))
        data["version"] = v
        data["protocol_version"] = pv
        manifest.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    print(f"[x.py] version: OpenFinger {v}, protocol v{pv}")


def cmake_configure(config: str, generator: str | None, arch: str | None) -> None:
    del config
    args = ["cmake", "-S", str(ROOT), "-B", str(BUILD)]
    if generator:
        args += ["-G", generator]
    if arch:
        args += ["-A", arch]
    run_process(args)


def cmake_build(config: str, target: str | None = None) -> None:
    args = ["cmake", "--build", str(BUILD), "--config", config]
    if target:
        args += ["--target", target]
    run_process(args)


def build_cpp(args: argparse.Namespace, target: str | None = None) -> None:
    generate_version_files()
    if args.stop:
        stop_processes(PROCESS_NAMES)
    if args.stop_steamvr:
        stop_processes(STEAMVR_PROCESS_NAMES)
    cmake_configure(args.config, args.generator, args.arch)
    cmake_build(args.config, target)


def build_gui(args: argparse.Namespace) -> None:
    generate_version_files()
    if not GUI_PROJECT.exists():
        raise FileNotFoundError(f"missing GUI project: {GUI_PROJECT}")
    run_process(["dotnet", "build", str(GUI_PROJECT), "-c", args.config])


def build_firmware_targets(board: str, flash: bool = False, port: str | None = None) -> None:
    boards = list(FIRMWARE_TARGETS.keys()) if board == "all" else [board]
    for current in boards:
        project_dir, env = FIRMWARE_TARGETS[current]
        cmd = ["pio", "run", "-d", str(project_dir), "-e", env]
        if flash:
            cmd += ["-t", "upload"]
            if port:
                cmd += ["--upload-port", port]
        run_process(cmd)


def gui_output_dir(config: str) -> Path:
    preferred = GUI_DIR / "bin" / config / "net10.0-windows10.0.26100.0"
    fallback = GUI_DIR / "bin" / config / "net10.0-windows"
    if preferred.exists():
        return preferred
    return fallback


def gui_exe_path(config: str) -> Path:
    return gui_output_dir(config) / "OpenFinger.Control.exe"


def launch_gui(config: str) -> None:
    exe = gui_exe_path(config)
    if not exe.exists():
        raise FileNotFoundError(f"GUI executable not found: {exe}")

    print(f"[x.py] launch {exe}")
    if os.name == "nt":
        subprocess.Popen([str(exe)], cwd=str(exe.parent))
    else:
        print(f"[x.py] GUI launch is only automatic on Windows. Built executable: {exe}")


def command_build(args: argparse.Namespace) -> None:
    build_cpp(args)
    build_gui(args)


def command_driver(args: argparse.Namespace) -> None:
    build_cpp(args, "driver_openfinger")


def command_service(args: argparse.Namespace) -> None:
    build_cpp(args, "openfinger_service")


def command_bridge(args: argparse.Namespace) -> None:
    build_cpp(args, "openfinger_controller_bridge")


def command_monitor(args: argparse.Namespace) -> None:
    build_cpp(args, "openfinger_adc_monitor")


def command_gui(args: argparse.Namespace) -> None:
    build_gui(args)


def command_firmware(args: argparse.Namespace) -> None:
    generate_version_files()
    build_firmware_targets(args.board, flash=args.flash, port=args.port)


def copytree_merge(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    for item in src.rglob("*"):
        rel = item.relative_to(src)
        out = dst / rel
        if item.is_dir():
            out.mkdir(parents=True, exist_ok=True)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, out)


def should_copy_runtime_file(path: Path) -> bool:
    if any(part in PACKAGE_EXCLUDE_DIRS for part in path.parts):
        return False
    if path.suffix.lower() in PACKAGE_EXCLUDE_SUFFIXES:
        return False
    return True


def copy_runtime_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(f"missing runtime directory: {src}")
    for item in src.rglob("*"):
        if item.is_dir() or not should_copy_runtime_file(item.relative_to(src)):
            continue
        rel = item.relative_to(src)
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, out)


def copy_file_if_exists(src: Path, dst: Path, required: bool = False) -> bool:
    if not src.exists():
        if required:
            raise FileNotFoundError(f"missing required file: {src}")
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def publish_gui(config: str, out_dir: Path, runtime: str) -> None:
    remove_tree(out_dir)
    run_process([
        "dotnet", "publish", str(GUI_PROJECT),
        "-c", config,
        "-r", runtime,
        "--self-contained", "false",
        "-o", str(out_dir),
    ])


def write_package_readme(out_root: Path, package_name: str, runtime: str) -> None:
    (out_root / "README.txt").write_text(
        f"""OpenFinger {version()}
Protocol v{protocol_version()}
Runtime: {runtime}
Package: {package_name}

Start here:
  OpenFinger.Control.exe

Package layout:
  OpenFinger.Control.exe      Main desktop application. Start OpenFinger from here.
  openfinger_service.exe      Background service used by the application.
  openfinger_controller_bridge.exe
                              SteamVR bridge helper.
  openfinger_adc_monitor.exe  ADC/debug helper.
  openfinger_firmware_tool.exe
                              Firmware flashing helper used by the application.
  FirmwarePackages\\          Bundled firmware files used by the GUI.
  Driver\\                    SteamVR driver package.
  docs\\                      Project documentation.

Notes:
  - Extract the zip before running OpenFinger.
  - Keep the files in this folder together; the GUI expects the helper tools and
    firmware packages to stay next to OpenFinger.Control.exe.
  - Most users only need to run OpenFinger.Control.exe.
""",
        encoding="utf-8",
    )


def collect_checksums(out_root: Path) -> list[dict[str, str | int]]:
    entries: list[dict[str, str | int]] = []
    for file in sorted(p for p in out_root.rglob("*") if p.is_file()):
        if file.name in {"checksums.sha256", "package-manifest.json"}:
            continue
        digest = hashlib.sha256(file.read_bytes()).hexdigest()
        rel = file.relative_to(out_root).as_posix()
        entries.append({"path": rel, "size": file.stat().st_size, "sha256": digest})
    return entries


def write_manifest(out_root: Path, package_name: str, runtime: str) -> None:
    files = collect_checksums(out_root)
    (out_root / "checksums.sha256").write_text(
        "".join(f"{item['sha256']}  {item['path']}\n" for item in files),
        encoding="utf-8",
    )
    manifest = {
        "name": "OpenFinger",
        "version": version(),
        "protocol_version": protocol_version(),
        "runtime": runtime,
        "package": package_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "entrypoint": "OpenFinger.Control.exe",
        "files": files,
    }
    (out_root / "package-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def create_zip_archive(src_dir: Path, archive: Path) -> None:
    if archive.exists():
        archive.unlink()
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for file in sorted(p for p in src_dir.rglob("*") if p.is_file()):
            zf.write(file, file.relative_to(src_dir.parent).as_posix())


def create_tar_gz_archive(src_dir: Path, archive: Path) -> None:
    if archive.exists():
        archive.unlink()
    with tarfile.open(archive, "w:gz") as tar:
        tar.add(src_dir, arcname=src_dir.name)


def command_package(args: argparse.Namespace) -> None:
    if not args.skip_build:
        command_build(args)

    v = version()
    runtime = args.runtime
    package_name = f"OpenFinger-{v}-{runtime}"
    out_root = DIST / package_name
    remove_tree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    # OpenFinger.Control is the product entry point, so publish it directly at
    # the package root. This keeps the GitHub asset usable after one extract:
    # users can open the folder and run OpenFinger.Control.exe immediately.
    publish_gui(args.config, out_root, runtime)

    native_dir = BUILD / args.config
    for name in PACKAGE_NATIVE_TOOLS:
        copy_file_if_exists(native_dir / name, out_root / name, required=True)
    for name in BRIDGE_RUNTIME_FILES:
        copy_file_if_exists(native_dir / name, out_root / name, required=False)

    copy_runtime_tree(DRIVER_ROOT, out_root / "Driver")
    for junk in (out_root / "Driver" / "bin" / "win64" / args.config,):
        remove_tree(junk)

    docs_dir = ROOT / "docs"
    if docs_dir.exists():
        copy_runtime_tree(docs_dir, out_root / "docs")
    copy_file_if_exists(ROOT / "README.md", out_root / "docs" / "README.md")
    copy_file_if_exists(ROOT / "CHANGELOG.md", out_root / "docs" / "CHANGELOG.md")
    copy_file_if_exists(ROOT / "LICENSE", out_root / "LICENSE")

    write_package_readme(out_root, package_name, runtime)
    # Keep machine-oriented files out of the user-facing archive. CI still uses
    # verify-package to validate the layout and critical files before upload.

    archives: list[Path] = []
    formats = ["zip", "tar.gz"] if args.archive_format == "both" else [args.archive_format]
    for fmt in formats:
        archive = DIST / f"{package_name}.{fmt}"
        if fmt == "zip":
            create_zip_archive(out_root, archive)
        elif fmt == "tar.gz":
            create_tar_gz_archive(out_root, archive)
        else:
            raise ValueError(f"unknown archive format: {fmt}")
        archives.append(archive)
        print(f"[x.py] package: {archive}")

    release_notes = DIST / "release-notes.md"
    release_notes.write_text(
        f"""# OpenFinger {v}

- Runtime: `{runtime}`
- Protocol: `v{protocol_version()}`
- Entrypoint: `OpenFinger.Control.exe`

Artifacts:
""" + "".join(f"- `{a.name}`\n" for a in archives) + "\nThis release was generated by `python x.py package`.\n",
        encoding="utf-8",
    )


def command_verify_package(args: argparse.Namespace) -> None:
    package_name = f"OpenFinger-{version()}-{args.runtime}"
    out_root = DIST / package_name
    required = [
        out_root / "OpenFinger.Control.exe",
        out_root / "openfinger_service.exe",
        out_root / "openfinger_controller_bridge.exe",
        out_root / "openfinger_adc_monitor.exe",
        out_root / "openfinger_firmware_tool.exe",
        out_root / "Driver" / "driver.vrdrivermanifest",
        out_root / "README.txt",
    ]
    missing = [path for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("package verification failed; missing: " + ", ".join(str(p) for p in missing))
    forbidden_root_files = [
        out_root / "package-manifest.json",
        out_root / "checksums.sha256",
        out_root / "VERSION",
        out_root / "PROTOCOL_VERSION",
    ]
    leaked = [path for path in forbidden_root_files if path.exists()]
    if leaked:
        raise FileExistsError("package contains internal files: " + ", ".join(str(p) for p in leaked))
    print(f"[x.py] package verified: {out_root}")

def command_run(args: argparse.Namespace) -> None:
    generate_version_files()
    build_cpp(args)
    build_gui(args)
    build_firmware_targets("all", flash=False, port=None)
    launch_gui(args.config)


def command_clean(args: argparse.Namespace) -> None:
    del args
    for path in (BUILD, DIST, GUI_DIR / "bin", GUI_DIR / "obj"):
        remove_tree(path)
    for project_dir, _ in FIRMWARE_TARGETS.values():
        remove_tree(project_dir / ".pio")


def command_version(args: argparse.Namespace) -> None:
    del args
    generate_version_files()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="OpenFinger build / firmware / package helper")
    parser.add_argument("command", nargs="?", default="build", choices=[
        "build", "driver", "service", "bridge", "monitor", "gui", "firmware", "package", "verify-package", "run", "clean", "version"
    ])
    parser.add_argument("--config", default="Debug", choices=["Debug", "Release", "RelWithDebInfo", "MinSizeRel"])
    parser.add_argument("--generator", default="Visual Studio 17 2022" if os.name == "nt" else None)
    parser.add_argument("--arch", default="x64" if os.name == "nt" else None)
    parser.add_argument("--stop", action=argparse.BooleanOptionalAction, default=os.name == "nt", help="stop OpenFinger processes before C++ build")
    parser.add_argument("--stop-steamvr", action="store_true", help="also stop vrserver/vrmonitor before build")
    parser.add_argument("--board", default="esp32c3", choices=["esp32c3", "esp32s3", "all"], help="firmware board target")
    parser.add_argument("--flash", action="store_true", help="upload firmware after build")
    parser.add_argument("--port", help="serial port for firmware flashing, for example COM5")
    parser.add_argument("--runtime", default="win-x64", help=".NET runtime identifier used by package/publish, for example win-x64")
    parser.add_argument("--archive-format", default="zip", choices=["zip", "tar.gz", "both"], help="package archive format")
    parser.add_argument("--skip-build", action="store_true", help="package existing build outputs without rebuilding")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    handlers = {
        "build": command_build,
        "driver": command_driver,
        "service": command_service,
        "bridge": command_bridge,
        "monitor": command_monitor,
        "gui": command_gui,
        "firmware": command_firmware,
        "package": command_package,
        "verify-package": command_verify_package,
        "run": command_run,
        "clean": command_clean,
        "version": command_version,
    }
    try:
        handlers[args.command](args)
        return 0
    except subprocess.CalledProcessError as exc:
        print(f"[x.py] command failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode
    except Exception as exc:
        print(f"[x.py] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
