namespace OpenFinger.Control;

public enum UpdateDialogChoice
{
    None,
    Later,
    Ignore,
    ViewRelease,
    Download
}

public partial class UpdateAvailableDialog : Window
{
    private const string GenericNotesFallback = "这次更新已准备好下载。";

    public UpdateDialogChoice Choice { get; private set; }

    public UpdateAvailableDialog(AppUpdateCheckResult update, bool previewMode = false)
    {
        InitializeComponent();

        DialogTitleText.Text = previewMode ? "更新提示预览" : "发现新版本";
        DialogDescriptionText.Text = previewMode
            ? "这是更新提示窗口的预览效果。真正检测到新版本时，看到的就是这类提示。"
            : "有新的 OpenFinger 版本可用。你可以现在更新，也可以稍后再处理。";

        CurrentVersionText.Text = $"v{AppUpdateService.NormalizeVersionText(update.CurrentVersion)}";
        LatestVersionText.Text = $"v{AppUpdateService.NormalizeVersionText(update.LatestVersion)}";
        PublishedText.Text = AppUpdateService.FormatPublishedText(update.PublishedAtUtc);

        var releaseName = BuildCompactReleaseName(update.ReleaseName, update.LatestVersion);
        ReleaseNameText.Text = releaseName ?? string.Empty;
        ReleaseNameText.Visibility = string.IsNullOrWhiteSpace(releaseName) ? Visibility.Collapsed : Visibility.Visible;

        var assetText = BuildCompactAssetText(update.AssetName);
        ReleaseAssetText.Text = assetText ?? string.Empty;
        ReleaseAssetText.Visibility = string.IsNullOrWhiteSpace(assetText) ? Visibility.Collapsed : Visibility.Visible;
        SummarySection.Visibility = ReleaseNameText.Visibility == Visibility.Visible || ReleaseAssetText.Visibility == Visibility.Visible
            ? Visibility.Visible
            : Visibility.Collapsed;

        var notesText = BuildCompactReleaseNotes(update.ReleaseNotes);
        ReleaseNotesText.Text = notesText;
        NotesSection.Visibility = string.Equals(notesText, GenericNotesFallback, StringComparison.Ordinal)
            ? Visibility.Collapsed
            : Visibility.Visible;

        var hasDirectPackage = !string.IsNullOrWhiteSpace(update.AssetDownloadUrl);
        DownloadButton.Content = hasDirectPackage ? "下载并更新" : "打开发行页";
        DownloadHintText.Text = hasDirectPackage
            ? "下载更新后会自动替换当前版本，并重新打开 OpenFinger。"
            : "这次发行版没有直接下载包，可以先查看发行页。";
    }

    private static string BuildCompactReleaseNotes(string? notes)
    {
        if (string.IsNullOrWhiteSpace(notes))
        {
            return GenericNotesFallback;
        }

        var lines = notes
            .Replace("\r\n", "\n")
            .Split('\n', StringSplitOptions.TrimEntries)
            .Select(CleanReleaseLine)
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .Where(line => !ShouldSkipReleaseLine(line))
            .Take(8)
            .ToArray();

        if (lines.Length == 0)
        {
            return GenericNotesFallback;
        }

        return string.Join(Environment.NewLine, lines.Take(4).Select(line => $"• {line}"));
    }

    private static string? BuildCompactReleaseName(string? releaseName, string latestVersion)
    {
        if (string.IsNullOrWhiteSpace(releaseName))
        {
            return null;
        }

        var trimmed = releaseName.Trim();
        return string.Equals(trimmed, $"OpenFinger {latestVersion}", StringComparison.OrdinalIgnoreCase)
            ? null
            : trimmed;
    }

    private static string? BuildCompactAssetText(string? assetName)
    {
        return string.IsNullOrWhiteSpace(assetName) ? null : $"安装包：{assetName}";
    }

    private static string CleanReleaseLine(string line)
    {
        var cleaned = line.Trim();
        while (cleaned.StartsWith("#", StringComparison.Ordinal)
               || cleaned.StartsWith("-", StringComparison.Ordinal)
               || cleaned.StartsWith("*", StringComparison.Ordinal))
        {
            cleaned = cleaned[1..].TrimStart();
        }

        return cleaned;
    }

    private static bool ShouldSkipReleaseLine(string line)
    {
        return line.StartsWith("OpenFinger ", StringComparison.OrdinalIgnoreCase)
               || line.StartsWith("Runtime:", StringComparison.OrdinalIgnoreCase)
               || line.StartsWith("Protocol:", StringComparison.OrdinalIgnoreCase)
               || line.StartsWith("Entrypoint:", StringComparison.OrdinalIgnoreCase)
               || line.StartsWith("Artifacts:", StringComparison.OrdinalIgnoreCase)
               || line.StartsWith("This release was generated by", StringComparison.OrdinalIgnoreCase)
               || line.Contains(".zip", StringComparison.OrdinalIgnoreCase)
               || line.Contains("artifact", StringComparison.OrdinalIgnoreCase);
    }

    private void OnLaterClick(object sender, RoutedEventArgs e)
    {
        Choice = UpdateDialogChoice.Later;
        DialogResult = false;
    }

    private void OnIgnoreClick(object sender, RoutedEventArgs e)
    {
        Choice = UpdateDialogChoice.Ignore;
        DialogResult = true;
    }

    private void OnViewReleaseClick(object sender, RoutedEventArgs e)
    {
        Choice = UpdateDialogChoice.ViewRelease;
        DialogResult = true;
    }

    private void OnDownloadClick(object sender, RoutedEventArgs e)
    {
        Choice = UpdateDialogChoice.Download;
        DialogResult = true;
    }
}
